# Site settings
title: Jaclyn Chen
email: jaclyn.y.chen | gmail
description: > # this means to ignore newlines until "baseurl:"
  iOS developer + traveler + Taiwanese = Jaclyn Chen
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jaclynchen.com/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
